export const SPAWN_TIMER_MAX = 5000;
export const DAMAGE_TIMER_MAX = 1000;
export const VICTORY_TIMER_MAX = 2000;
export const FPS_PRINT_TIMEOUT = 2000;

export const FRANK_CHARGE_TIMER_MAX = 1500;
export const FRANK_CHARGE_COOLDOWN_TIMEOUT = 5000;
export const FRANK_MULTI_HEAD_TIMEOUT = 100;
